export const STUDENT_ADD_DATA="STUDENT_ADD_DATA"

export const STUDENT_DELETE_DATA="STUDENT_DELETE_DATA"

export const TEST_ADD_DATA="TEST_ADD_DATA"

export const TEST_DELETE_DATA="TEST_DELETE_DATA"

export const TEST_GET_DATA="TEST_GET_DATA"

export const STUDENT_GET_DATA="STUDENT_GET_DATA"

export const STUDENT_SEARCH_GET_DATA="STUDENT_SEARCH_GET_DATA"

export const STUDENT_QUERY_GET_DATA="STUDENT_QUERY_GET_DATA"

export const STUDENT_TEST_UPDATE_DATA="STUDENT_TEST_UPDATE_DATA"